# Generated by Django 5.0.6 on 2024-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phoneNo', models.IntegerField()),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
